package interactif

import "fmt"

// this package will contain all the functions to interact with the user
// it will be used by the main.go file
var SecretFieldNames = []string{"Username", "Credential", "URL", "LastUpdate", "LastUpdateBy", "Comment"}
var SecretHumanFieldNames = []string{"Username", "Credential", "URL", "Comment"}

// select  smartcard type
func SelectSmartcard() string {
	var smartcard string
	fmt.Println("Select Smartcard (Default is Yubikey)")
	fmt.Println("1. Yubikey")
	fmt.Println("2. Nitrokey")
	fmt.Println("3. Other")
	fmt.Print("Enter Smartcard Number: ")
	var smartcardNumber int
	fmt.Scanln(&smartcardNumber)
	switch smartcardNumber {
	case 1:
		smartcard = "yubikey"
	case 2:
		smartcard = "nitrokey"
	case 3:
		smartcard = "other"
	default:
		smartcard = "yubikey"
	}
	return smartcard
}

// this function will ask the user to enter the value of the field and return the value as map[string]string
func AskUserwithPrevious(Previous []map[string]string) map[string]string {
	fieldValues := make(map[string]string)

	for key, field := range Previous[0] {
		var value string
		if key == "Credential" {
			rndPwd := "ee" //crypto.randomPassword(12, true, true, true, true, "!@#$%^&*()_+-")
			fmt.Printf("Enter %s: (%s) (* if you want random) ", key, field)
			fmt.Scanln(&value)
			if value == "*" {
				value = rndPwd
			} else if value == "" {
				value = field
			}
			fieldValues[key] = value
		} else {
			fmt.Printf("Enter %s: (%s) ", key, field)

			fmt.Scanln(&value)
			if value == "" {
				value = field
			}
		}
		fieldValues[key] = value
	}
	return fieldValues

}

// this function will ask the user to enter the value of the field and return the value as map[string]string
func AskUser() map[string]string {
	fieldValues := make(map[string]string)
	for _, field := range SecretHumanFieldNames {
		var value string
		if field == "Credential" {
			rndPwd := "" //randomPassword(10, true, true, true, true, "!@#$%^&*()_+-")
			fmt.Printf("Enter %s (or hit enter to have autogenerated) ", field)
			fmt.Scanln(&value)
			if value == "" {
				value = rndPwd
			}
		} else {
			fmt.Printf("Enter %s: ", field)
			fmt.Scanln(&value)
		}
		fieldValues[field] = value
	}
	return fieldValues
}

// ask for username and password and return them
func ReadUsernamePassword() (string, string) {
	fmt.Print("Enter Username: ")
	var username string
	fmt.Scanln(&username)
	fmt.Print("Enter Password: ")
	var password string
	fmt.Scanln(&password)
	return username, password
}
